### PR TITLE
Set version info when building releases

### LINKED ISSUE #441: Version command is fail
**Motivation**

When releasing the pulsarctl, the scripts don't add the version flags so we can not know the pulsarctl version. We should add the flags in the build scripts.

### PR DESCRIPTION
**Pull request by zymap**
---

Fixes #441

*Motivation*

Set the version flags when builing the release assets

### CODE REVIEW

File: scripts/build.sh [hunk 1]
```diff
@@ -10,78 +10,36 @@ if [[ "x$version" == "x" ]]; then
...
-function build_amd64_linux() {
-  DIR=pulsarctl-amd64-linux
-  mkdir ${DIR}
-  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o pulsarctl -ldflags "-X github.com/streamnative/pulsarctl/pkg/pulsar.ReleaseVersion=Pulsarctl-Go-$version" .
-  mv pulsarctl ${DIR}
-  cp -r plugins ${DIR}
-  tar -czf ${DIR}.tar.gz ${DIR}
-  mv ${DIR}.tar.gz $ASSETSDIR
-}
+ROOT_DIR=`cd $(dirname $0)/../; pwd`
```
Comment (nodece) [inline scripts/build.sh:13]: I think use the `git rev-parse --show-toplevel` is better.

File: scripts/build.sh [hunk 2]
```diff
@@ -10,78 +10,36 @@ if [[ "x$version" == "x" ]]; then
...
+
+build() {
+    local arch=${1}
+    local os=${2}
+    local base_dir=dist
+    local dirname=pulsarctl-${arch}-${os}
+    local dir=${base_dir}/${dirname}
+    mkdir -p ${dir}
+    CGO_ENABLED=0 GOOS=${os} GOARCH=${arch} go build \
+        -ldflags "${LDFLAGS}" -o pulsarctl
```
Comment (nodece) [inline scripts/build.sh:36]: you can output the `pulsarctl` to `${dir}/pulsarctl` .

File: scripts/build.sh [hunk 3]
```diff
@@ -10,78 +10,36 @@ if [[ "x$version" == "x" ]]; then
...
-function build_arm64_darwin() {
-  DIR=pulsarctl-arm64-darwin
-  mkdir ${DIR}
-  CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o pulsarctl -ldflags "-X github.com/streamnative/pulsarctl/pkg/pulsar.ReleaseVersion=Pulsarctl-Go-$version" .
-  mv pulsarctl ${DIR}
-  cp -r plugins ${DIR}
-  tar -czf ${DIR}.tar.gz ${DIR}
-  mv ${DIR}.tar.gz $ASSETSDIR
-}
+LDFLAGS+="-X \"github.com/streamnative/pulsarctl/pkg/cmdutils.ReleaseVersion=${version}\" "
```
Comment (ericsyh) [inline scripts/build.sh:17]: It will be duplicate to set LDFLAGS in `build.sh` again since Makefile has already set LDFLAGS. 
If we want to add a field in version print, we need to modify the `build.sh` and Makefile together.
I prefer to move the build logic from `build.sh` to Makefile, and use the make command in `build.sh` to triggle.

Take  `build_amd64_linux` for example:

In the Makefile, we can add

```
amd64_linux:
     CGO_ENABLED=0 GOOS=linux GOARCH=amd64 $(GOBUILD) -ldflags '$(LDFLAGS)' -o bin/pulsarctl
```

In the `build.sh`, it will be

```
function build_amd64_linux() {
  DIR=pulsarctl-amd64-linux
  mkdir ${DIR}
  make amd64_linux
  mv pulsarctl ${DIR}
  cp -r plugins ${DIR}
  tar -czf ${DIR}.tar.gz ${DIR}
  mv ${DIR}.tar.gz $ASSETSDIR
}

```

File: scripts/build.sh [hunk 4]
```diff
@@ -10,78 +10,36 @@ if [[ "x$version" == "x" ]]; then
...
+LDFLAGS+="-X \"github.com/streamnative/pulsarctl/pkg/cmdutils.BuildTS=$(date -u '+%Y-%m-%d %H:%M:%S')\" "
+LDFLAGS+="-X \"github.com/streamnative/pulsarctl/pkg/cmdutils.GitHash=$(git rev-parse HEAD)\" "
+LDFLAGS+="-X \"github.com/streamnative/pulsarctl/pkg/cmdutils.GitBranch=$(git rev-parse --abbrev-ref HEAD)\" "
+LDFLAGS+="-X \"github.com/streamnative/pulsarctl/pkg/cmdutils.GoVersion=$(go version)\" "
```
Comment (ericsyh) [inline scripts/build.sh:21]: It will be duplicate to set LDFLAGS in `build.sh` again since Makefile has already set LDFLAGS. If we want to add/modify a field in version print later, we need to modify the `build.sh` and Makefile together.
I prefer to move the build logic from `build.sh` to Makefile, and use the make command in `build.sh` to triggle.

Take  `build_amd64_linux` for example:

In the Makefile, we can add

```
amd64_linux:
     CGO_ENABLED=0 GOOS=linux GOARCH=amd64 $(GOBUILD) -ldflags '$(LDFLAGS)' -o bin/pulsarctl
```

In the `build.sh`, it will be

```
function build_amd64_linux() {
  DIR=pulsarctl-amd64-linux
  mkdir ${DIR}
  make amd64_linux
  mv pulsarctl ${DIR}
  cp -r plugins ${DIR}
  tar -czf ${DIR}.tar.gz ${DIR}
  mv ${DIR}.tar.gz $ASSETSDIR
}

```

File: scripts/build.sh (hunk 1 above)
Comment (zymap) [reply scripts/build.sh:13]: `git` command will make it only run with a git repo. `dirname` can run it anywhere.

**Review by nodece — APPROVED** [review]

**Comment by nodece** [comment]
@zymap I checked this RP strictly, I found no use this script in anywhere, you should use this script in `.github/workflows/ci-release-checks.yml` to instead of `build` and `build-site`.
