### PR TITLE
fix: fix token exp

### LINKED ISSUE #973: Non-expiring tokens contain "exp" claim of 0
Since the merge of #906, generated tokens that do not specify an expiration time contain an "exp" claim of 0:

```
{
  "exp": 0,
  "sub": "broker-admin"
}
```
Being the start of the epoch, this causes the token to be invalid as soon as it is issued. When used in conjunction with the ```prepare_helm_release.sh``` script of the [Pulsar Helm chart](https://github.com/apache/pulsar-helm-chart/blob/master/scripts/pulsar/prepare_helm_release.sh) to deploy Pulsar with auth enabled, broker pods fail to start with ```HTTP 401 Unauthorized``` errors. Removing the "exp" claim (as per the previous behavior) should indicate non-expiry. Doing so via the second workaround below allows the broker pods to start normally.

The Helm chart's ```prepare_helm_release.sh``` script auto-downloads and uses pulsarctl v0.5.0 by default, so perhaps many users will not encounter this problem. I prefer to keep pulsarctl more up-to-date, and recently ran into this issue during a Pulsar deployment.

**Workarounds:**

- Manually re-issue tokens with a valid expiration time using a current release of pulsarctl
- Manually re-issue non-expiring tokens using an older version of pulsarctl (before #906)
- Allow the Pulsar Helm chart prep script to continue to auto-download and use version 0.5.0

### PR DESCRIPTION
**Pull request by nodece**
Fixes #973

### Motivation

https://github.com/streamnative/pulsarctl/pull/906 breaks the token expiration. When a user doesn't set up the expiration, we should not add the `exp` field to the JWT payload.

### Modifications

- Check `expireTime` to determine whether to add `exp` filed to the JWT payload

### Verifying this change

- [x] Make sure that the change passes the CI checks.

Added `token_test.go` test

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: pkg/pulsar/token.go [hunk 1]
```diff
@@ -84,10 +84,18 @@ func (t *token) CreateSecretKey(signatureAlgorithm algorithm.Algorithm) ([]byte,
 func (t *token) Create(algorithm algorithm.Algorithm, signKey interface{}, subject string,
 	expireTime int64) (string, error) {
 
-	claims := &jwt.MapClaims{
-		"sub": subject,
-		"exp": jwt.NewNumericDate(time.Unix(expireTime, 0)),
+	var claims *jwt.MapClaims
+	if expireTime == 0 {
```
Comment (tuteng) [inline pkg/pulsar/token.go:88]: Do you need to check if it is less than 0?

Comment (nodece) [reply pkg/pulsar/token.go]: Done.

**Review by tuteng — APPROVED** [review]

**Review by zymap — APPROVED** [review]
